Modified on-ramp intent generation
AlphaWallet/alpha-wallet-android pull request #1746
Opened 2021-02-26 08:39 UTC by justindg

This PR addresses #1738 
- All fiat on-ramp provider data will now be maintained in a file named '**onramp_contracts.json**'. Each item will contain the token symbol, contract address, and on-ramp provider (ie Ramp, Wyre, etc)
- FunctionBar button for '**Buy XXX**' now automatically generates label depending on token symbol. This is to prevent bloating the code with multiple if/else statements and corresponding string resources for each kind of token. If a token is not in the known contracts file, it will display '**Buy Crypto**'.

2021-03-01 10:45 UTC, JamesSmartCell requested changes

2021-03-02 11:32 UTC, justindg commented
Hi @JamesSmartCell , thanks for the feedback! I've decided to rework the feature a bit, I'll explain the rationale below.

I have opted to create an `OnRampRepository` class which means the Buy feature is not longer tied to the `FunctionButtonBar` class. In the future, this will make it easier to integrate the 'Buy' feature into any Activity or Fragment via injection. Since the feature is supposed to be dynamic, I thought it would be a good idea not to lump it with the "standard functions". This has greatly reduced clutter in the FunctionButtonBar class as well. The `OnRampRepository` class handles everything from reading through the known contracts file to `Intent `generation. This should be easier to extend in the future than the original implementation.

Since I've created it in a way it could be reused easily (and without being dependent on the FunctionButtonBar), the click handler should be through a new interface `BuyCryptoInterface`, which should be implemented in any `Activity `or `Fragment` that needs a Buy feature. It has a sole method of `void handleBuyFunction(Token token);`

I hope this change has relieved some of the pain points mentioned earlier. Please let me know if you have comments or suggestions.

2021-03-02 11:32 UTC, justindg commented on app/src/main/java/com/alphawallet/app/widget/FunctionButtonBar.java
Resolved

2021-03-02 11:33 UTC, justindg commented on app/src/main/java/com/alphawallet/app/widget/FunctionButtonBar.java
> +
I completely misunderstood this function before, but I have now reverted the change in the new commit.

2021-03-02 11:33 UTC, justindg commented on app/src/main/java/com/alphawallet/app/widget/FunctionButtonBar.java
> +    private OnRampContract findContract(String address)
Reworked the json file, by using the contract address as the key. Please let me know if this works for you

2021-03-02 13:47 UTC, AW-STJ commented
@JamesSmartCell 

Would you be able to add the MixPanel events as well?

We should measure the usage of deeplinks for the different buying options provided

2021-03-03 23:46 UTC, AW-STJ commented
Hey Justin, I tested and it works as expected. Waiting for more feedback from team if any.

In the meantime, I have some cosmetic changes.

I want to remove the "from Ramp" from the Buy button for all tokens.
Buy ETH "from Ramp" --> Buy ETH
Buy xDAI "from Ramp" --> Buy xDAI etc.

2021-03-03 23:47 UTC, JamesSmartCell commented
@justindg can you have a look at adding the mixpanel events? You need to inject ```AnalyticsServiceType``` into the ERC20detail viewModel, then when the 'buy' button is clicked you just log the event as per ```analyticsService.track(...```

2021-03-03 23:54 UTC, JamesSmartCell commented
@jus

> Hi @JamesSmartCell , thanks for the feedback! I've decided to rework the feature a bit, I'll explain the rationale below.
> 
> I have opted to create an `OnRampRepository` class which means the Buy feature is no longer tied to the `FunctionButtonBar` class. In the future, this will make it easier to integrate the 'Buy' feature into any Activity or Fragment via injection. Since the feature is supposed to be dynamic, I thought it would be a good idea not to lump it with the "standard functions". This has greatly reduced clutter in the `FunctionButtonBar ` class, as well as the corresponding` Activities/ViewModels` that have the feature. The `OnRampRepository` class handles everything from reading through the known contracts file to `Intent `generation. This should be easier to extend in the future than the original implementation.
> 
> Since I've created it in a way it could be reused easily (and without being dependent on the FunctionButtonBar), the click handler should be through a new interface `BuyCryptoInterface`, which should be implemented in any `Activity `or `Fragment` that needs a Buy feature. It has a sole method of `void handleBuyFunction(Token token);`
> 
> A few examples that this can be easily integrated would be:
> 
> * Adding a 'Buy Crypto' option via the SettingsFragment
> * Adding a shortcut/icon to buy within the DAppBrowserFragment
> 
> I hope this change has relieved some of the pain points mentioned earlier. Please let me know if you have comments or suggestions.

@justindg Yes this looks very clean now, nice :)

Can you fix the button text as per @AW-STJ's request and add the analytics call to your new OnRampRepo class. Suggest to use something like this:

```
AnalyticsProperties analyticsProperties = new AnalyticsProperties();
analyticsProperties.setData([symbol of token being purchased]);
analyticsService.track(C.AN_USE_ONRAMP, analyticsProperties);
```

Where AN_USE_ONRAMP is just something like 'Use Onramp'. This is just for ease of finding the new data type in the analytics dump.

2021-03-04 03:22 UTC, JamesSmartCell approved these changes

2021-03-04 03:24 UTC, merged