Add logic to separate mainnet and testnet coins
AlphaWallet/alpha-wallet-android pull request #1810
Opened 2021-04-17 18:58 UTC by ChintanRathod

Fixes #1804

2021-04-17 18:59 UTC, ChintanRathod commented
@JamesSmartCell This PR has no following changes as has new design. 

![image](https://user-images.githubusercontent.com/4371780/115123932-1abb3f80-9fdd-11eb-8bc6-ce577ef5e8d7.png)

2021-04-18 07:16 UTC, JamesSmartCell requested changes
Looks good! Can you just fix the two typos and I'll push it.

2021-04-18 07:16 UTC, JamesSmartCell commented on app/src/main/java/com/alphawallet/app/repository/SharedPreferenceRepository.java
>      public static final String FULL_SCREEN_STATE = "full_screen";
Typo

2021-04-18 07:16 UTC, JamesSmartCell commented on app/src/main/res/values/strings.xml
> +    <string name="mainnett">Mainnet</string>
typo (mainnet)

2021-04-18 07:28 UTC, ChintanRathod commented on app/src/main/java/com/alphawallet/app/repository/SharedPreferenceRepository.java
>      public static final String FULL_SCREEN_STATE = "full_screen";
Done

2021-04-18 07:28 UTC, ChintanRathod commented on app/src/main/res/values/strings.xml
> +    <string name="mainnett">Mainnet</string>
Done

2021-04-18 23:20 UTC, JamesSmartCell requested changes
Just one issue I noticed: When starting the wallet for the first time with this patch, it was still showing all the testnets and mainnets.

Can you add a pass-over the selected networks at runtime in HomeViewModel to ensure that either only testnet or mainnet is selected depending on the switch setting.

2021-04-19 02:58 UTC, ChintanRathod commented
I guess I know the problem for fresh installation. Looking into it.

2021-04-19 03:03 UTC, ChintanRathod commented
@JamesSmartCell When I do fresh installation, I got this screen. Could you confirm this is the same you got?

![image](https://user-images.githubusercontent.com/4371780/115176010-cb166a00-a0e9-11eb-99aa-f1185b39c082.png)

Because this is perfect implementation as expected. I found no issue with the patch.

2021-04-19 03:11 UTC, ChintanRathod commented
I accidently changed the layout and didn't notice the use of the same layout in other activities. So created separate layout file for the SelectNetwork activity and revert the activity_list changes.

2021-04-19 03:27 UTC, JamesSmartCell commented
Hi @ChintanRathod no the opposite, it's for existing installation. Say you have a lot of networks selected, you upgrade to a version with this feature, but still all testnet and mainnet tokens are together until you go to the 'selectnetwork' screen.

2021-04-19 03:29 UTC, ChintanRathod commented
Ok. Let me try to install older app and try with this new one.

2021-04-19 03:29 UTC, hboon commented
BTW, don't forget to check the dapp browser (and WalletConnect connection screen) in case those are affected.

2021-04-19 03:31 UTC, JamesSmartCell commented
> BTW, don't forget to check the dapp browser (and WalletConnect connection screen) in case those are affected.

Yes I checked that, that code isn't touched so it should still work as before, but I'll check before pushing

2021-04-19 03:37 UTC, hboon commented
> > BTW, don't forget to check the dapp browser (and WalletConnect connection screen) in case those are affected.
> 
> Yes I checked that, that code isn't touched so it should still work as before, but I'll check before pushing

Ok. But just in case: I mean like if you enable mainnets in Settings, dapp browser shouldn't let you switch to a testnet. Similarly for WalletConnect.

2021-04-19 04:03 UTC, JamesSmartCell commented
> > > BTW, don't forget to check the dapp browser (and WalletConnect connection screen) in case those are affected.
> > 
> > 
> > Yes I checked that, that code isn't touched so it should still work as before, but I'll check before pushing
> 
> Ok. But just in case: I mean like if you enable mainnets in Settings, dapp browser shouldn't let you switch to a testnet. Similarly for WalletConnect.

It won't let you do that; you can't switch to a network that's not active.

When the PR is complete I'll test disabling a network that is currently active too.

2021-04-21 07:54 UTC, JamesSmartCell approved these changes

2021-04-21 07:55 UTC, merged