Improve network selection flow [wip]
AlphaWallet/alpha-wallet-android pull request #1830
Opened 2021-05-08 13:08 UTC by justindg

[wip]

2021-05-09 23:40 UTC, JamesSmartCell requested changes
Sorry about the confusion, my mistake I should drink coffee in the morning before looking at PRs!

So, in summary all that needs changing is:

1. when you exit from the SelectNetworkActivity, call the RESET_WALLET message as previously was in there - otherwise, you may still be showing testnet/mainnet  tokens after the switch.
2. No need to use 'hasRealValue' and 'isTestNet', as they are always boolean opposite.

I think that's it.

2021-05-10 00:48 UTC, justindg commented
Hi @JamesSmartCell, regarding (1), I intended to display all mainnets/testnets in single selection mode because I saw this comment from @colourfreak in the original thread: https://github.com/AlphaWallet/alpha-wallet-android/issues/1804#issuecomment-824068805, also in [Zeplin](https://app.zeplin.io/project/5d088205bff2d15de6a4397b/screen/608026cdd784971b6b2c0b01). Can you please confirm this?

Regarding (2) - this can easily be done however I don't see this particular interaction in Zeplin

2021-05-10 16:40 UTC, justindg commented on app/src/main/java/com/alphawallet/app/repository/EthereumNetworkBase.java
Resolved

2021-05-14 10:46 UTC, JamesSmartCell commented
Thankyou @justindg. It now works perfectly and code is cleaner than when you started.

2021-05-14 10:46 UTC, JamesSmartCell approved these changes

2021-05-14 10:47 UTC, merged