Fixed Wallet address truncate
AlphaWallet/alpha-wallet-android pull request #1916
Opened 2021-07-08 07:46 UTC by ChintanRathod

Fixes #1900

2021-07-08 11:23 UTC, JamesSmartCell requested changes
It fixes the problem but it looks terrible.

The address text should almost line up, as per the spec.

2021-08-02 01:27 UTC, whogonestopme662901 approved these changes

2021-08-02 01:27 UTC, whogonestopme662901 commented on app/src/main/res/layout/activity_transaction_success.xml
> +            android:layout_marginHorizontal="@dimen/dp22"
```suggestion
            android:layout_marginHorizontal="@dimen/dp22"
```

2021-08-04 04:31 UTC, JamesSmartCell commented
![address2](https://user-images.githubusercontent.com/12689544/128122015-247a8bde-1d3d-48e0-a8f5-163cc66b29a7.jpg)

Hi @whogonestopme662901 thanks for the PR update :)

Please see the attached picture; the left justified address doesn't really fit the overall aesthetic of the page.

At minimum; the text should be centred, but ideally, the two address lines would be the same length. In some phones; two lines wouldn't be enough so you'd need three.

2021-08-13 06:49 UTC, JamesSmartCell approved these changes

2021-08-13 06:53 UTC, merged