implemented load of assets from the alpha wallet repo first #1998
AlphaWallet/alpha-wallet-android pull request #2002
Opened 2021-09-08 09:20 UTC by mpaschenko

2021-09-09 03:40 UTC, JamesSmartCell requested changes
Can you refactor this in a slightly different way:

Can you restore the code in the original 'displayTokenIcon' and do it this way:

1. Utils.getTokenImageUrl returns the path to AW repo (code should now be much simpler).
2. Fold CircleCrop into the Glide call (first check always AW)
3. If RQ listener gets an 'onLoadFailed' then try to load the Trust icon so you'll need a new function in class Utils as Trust repo needs the chain name, based on the existing getTokenImageUrl. To load the icon, pull the address from the 'model', and match it against the current 'Token token'. If same, proceed, if different then just bail out without an update (RecyclerView reclaimed the icon before it could finish loading).
4. Remove the 'assetSvs.storeImageUrl' from the requestListenerAW onResourceReady, because we'll always be trying AW first so no need for this shortcut. Don't add it into the Trust repo as we want to prioritise our repo first and if the asset is added it should replace the Trust asset.

Note that the assetDefinition.fetchIconForToken in the bindData method is for ERC721 and ERC1155 tokens where we've read the data from the token. Any AW repo icon should override this, so only try this URL after trying AW.

It'll need a little re-code but if it follows the above rules it should be fine.

2021-09-09 14:36 UTC, mpaschenko commented
@JamesSmartCell I made changes as you requested, but icons start blinking from time to time **icon <> text** icon, can't get the clue why, will look more tomorrow.

2021-09-10 00:59 UTC, JamesSmartCell commented
Thanks, it only needed a small update, can you continue with Samoa - TokenIcon can be a big time sink.

2021-09-10 01:54 UTC, JamesSmartCell approved these changes

2021-09-10 01:55 UTC, merged