fix e2e
AlphaWallet/alpha-wallet-android pull request #2454
Opened 2022-03-21 02:08 UTC by seabornlee

- Fix test
- Convert androidTest to Unit test
- Transfer token from existing test wallet to new wallet and check balance
- Run tests with GitHub actions

2022-03-22 00:43 UTC, bsgarage45 commented
> * androidTest'i Birim testine dönüştür
> * Token'ı mevcut test cüzdanından yeni cüzdana aktarın ve bakiyeyi kontrol edin
> * Test başarısız olduğunda logcat ve ekran görüntüsünü toplayın
> * GitHub eylemleriyle testleri çalıştırın

gh pr checkout 2454

2022-03-30 02:21 UTC, JamesSmartCell commented
@seabornlee would you be able to resolve the conflicts?

2022-03-30 02:21 UTC, JamesSmartCell requested changes
Resolve merge conflicts

2022-04-08 10:16 UTC, JamesSmartCell approved these changes
This is awesome ...

2022-04-08 10:18 UTC, merged