Change Add Token to Add.
AlphaWallet/alpha-wallet-android pull request #2571
Opened 2022-04-22 02:17 UTC by vfbiby

#2236

2022-04-22 03:53 UTC, JamesSmartCell requested changes
Hi @vfbiby thankyou for the submission.

To complete the change you'd need to change the string resources.

So, you've updated the string resource pointer, now you have to update all the actual string resources.

You can find these in the res/values/strings directory in the AndroidStudio project.

We have the default English, and also Chinese, French, Spanish, Vietnamese and Burmese. These other languages need to be updated too; you could try using Google Translate for each of them.

2022-04-23 01:49 UTC, vfbiby commented
action_add exists already, I deleted action_add_token, because there is no reference.

2022-04-25 11:15 UTC, JamesSmartCell commented
Ah ok, I see what you did previously.

Thanks for the update, transactions are great.

2022-04-25 11:15 UTC, JamesSmartCell approved these changes

2022-04-25 11:16 UTC, merged