Implement Swap via LIFI
AlphaWallet/alpha-wallet-android pull request #2623
Opened 2022-05-25 04:34 UTC by justindg

This branch most likely needs more refining - would love to get comments so I could further improve it.

Remaining key pieces:

- Translate gas fee into digestible information
- Send web3 transaction (Web3Transaction object is already built in SwapViewModel)

2022-05-25 04:43 UTC, hboon commented
Polyon is cheaper to test :P

2022-06-28 17:35 UTC, JamesSmartCell requested changes

2022-06-30 06:54 UTC, justindg commented on app/src/main/res/layout/token_selector.xml
> +
Done

2022-06-30 06:54 UTC, justindg commented on app/src/main/java/com/alphawallet/app/widget/ConfirmSwapDialog.java
> +        return widget;
Done

2022-06-30 06:55 UTC, justindg commented on app/src/main/java/com/alphawallet/app/viewmodel/SwapViewModel.java
> +        {
In LIFI, the native token's address is 0xeee or 0x000. In AlphaWallet's Token object the address is the wallet address, so this check is needed

2022-06-30 07:12 UTC, justindg commented on app/src/main/java/com/alphawallet/app/widget/ConfirmSwapDialog.java
> +
Gas fee is already shown in a separate widget. This is supposedly for other fees (AW commission?) but I don't think those are available yet

2022-06-30 21:14 UTC, JamesSmartCell approved these changes

2022-06-30 21:15 UTC, merged

2022-07-01 10:51 UTC, JamesSmartCell commented on app/src/main/java/com/alphawallet/app/widget/ConfirmSwapDialog.java
> +
Ok gas estimate etc is already provided in the Quote return. I added it in already.