UX Update
AlphaWallet/alpha-wallet-android pull request #2660
Opened 2022-06-15 07:01 UTC by justindg

WIP - currently testing / cross-checking with new zeplin screens

2022-06-20 10:17 UTC, seabornlee requested changes

2022-06-20 10:19 UTC, seabornlee commented
Awesome!

2022-06-21 01:30 UTC, justindg commented
Ready for review!

2022-06-25 10:32 UTC, merged

2022-06-26 16:30 UTC, seabornlee reviewed
Thx