Show average and floor price, if available
AlphaWallet/alpha-wallet-android pull request #2708
Opened 2022-07-08 03:39 UTC by justindg

- Closes #2683

2022-07-09 08:26 UTC, JamesSmartCell requested changes

2022-07-09 13:43 UTC, JamesSmartCell commented
@justindg what are we using the collection call for? Can we get this info from the main opensea call? Or is this for the times when for some reason we don't have the opensea data?

2022-07-10 00:56 UTC, justindg commented
> @justindg what are we using the collection call for? Can we get this info from the main opensea call? Or is this for the times when for some reason we don't have the opensea data?

The main opensea call (`/asset/{address}`) contains the `average_price`, but for some reason it returns a `0` value for `floor_price`, hence I chained the collection call where we could find more accurate data.

2022-07-10 00:59 UTC, justindg commented on app/src/main/java/com/alphawallet/app/viewmodel/TokenFunctionViewModel.java
> +
I store the asset even if the collection check fails, I moved it to the end of `onCollection()` method

2022-07-10 20:31 UTC, JamesSmartCell commented on app/src/main/java/com/alphawallet/app/viewmodel/TokenFunctionViewModel.java
> +
> I store the asset even if the collection check fails, I moved it to the end of `onCollection()` method

Yes, that would be better I think. Also ensure that the screen is refreshed if required, even if collection fails. Might be an edge condition but worth doing.

2022-07-13 09:07 UTC, JamesSmartCell approved these changes

2022-07-13 09:07 UTC, merged