Swap update
AlphaWallet/alpha-wallet-android pull request #2732
Opened 2022-07-19 02:43 UTC by justindg

Fixes #2692

2022-07-20 10:55 UTC, JamesSmartCell commented
@justindg this is great, there's only one small issue I found:

While I have the confirmation dialog open, I don't want the 'Fetching Quote' update to interrupt it.

2022-07-20 15:08 UTC, seabornlee commented
Awesome @justindg, some minor feedback, if you have any question writing unit test, please DM me.

2022-07-20 16:02 UTC, JamesSmartCell commented
> Awesome @justindg, some minor feedback, if you have any questions about writing the unit test, please DM me.

Yes we will need to make writing unit tests for features a requirement for submitting PR. It may not be practical for some PRs but most allow for unit tests.

2022-07-22 02:36 UTC, seabornlee requested changes

2022-07-22 02:36 UTC, seabornlee commented on app/src/main/java/com/alphawallet/app/util/SwapUtils.java
> +    public static final String GAS_PRICE_FORMAT = "%s %s";
These constants can be private.

2022-07-22 02:36 UTC, seabornlee commented on app/src/main/java/com/alphawallet/app/util/SwapUtils.java
> +    public static String getCurrentPrice(Quote quote)
This method can move to class `Quote` and convert to an instance method.

2022-07-22 18:17 UTC, JamesSmartCell approved these changes

2022-07-22 18:19 UTC, JamesSmartCell approved these changes

2022-07-22 18:19 UTC, JamesSmartCell commented
@seabornlee can you approve and merge?

2022-07-25 02:34 UTC, seabornlee approved these changes

2022-07-25 02:34 UTC, merged

2022-07-25 02:34 UTC, seabornlee commented
Perfect! Thanks @justindg !