Prompt user to select networks upon creating/importing new wallet
AlphaWallet/alpha-wallet-android pull request #2751
Opened 2022-07-29 02:21 UTC by justindg

2022-07-29 17:29 UTC, JamesSmartCell requested changes
Issues found:

- After clicking "create New Wallet", app goes to the "name wallet" screen but it's not clear why or what user is supposed to do here (I was initially confused about what was meant to happen here. If we are going to do a "name wallet" it might be better to have a pop-up with only "write name for wallet" on it, so user knows exactly what's going on).

- I selected a few mainnet and testnet ( the default mainnet selection is a little bit odd, the default had Gnosis selected only), when I was on wallet screen I saw all the networks I selected (main and testnet). When I did a swipe refresh I could see only mainnet (I had last been selecting mainnet). Recommend that on the network selection with this option selected, we show mainnets then testnets, without any switch (ie all on same listview). When user exits back to the wallet page, it should show the mainnets only.

Once this is working let's update it so that it matches the new spec Tomek designed; this will have to be done carefully though.

2022-08-01 06:57 UTC, seabornlee commented
@JamesSmartCell I am adding more unit tests.

2022-08-01 09:36 UTC, seabornlee commented
@justindg Please also try to modify e2e test, I added it https://github.com/AlphaWallet/alpha-wallet-android/pull/2751/commits/fed2a83556e53bed413e08b8702187d250b3d11e
You can run it by start emulator and run shell `sh e2e.sh`.

2022-08-01 09:47 UTC, justindg commented
> @justindg Please also try to modify e2e test, I added it [fed2a83](https://github.com/AlphaWallet/alpha-wallet-android/commit/fed2a83556e53bed413e08b8702187d250b3d11e) You can run it by start emulator and run shell `sh e2e.sh`.

Thanks Seaborn, yes I will! Still working on the feature

2022-08-05 01:56 UTC, justindg commented
> Issues found:
> 
> * After clicking "create New Wallet", app goes to the "name wallet" screen but it's not clear why or what user is supposed to do here (I was initially confused about what was meant to happen here. If we are going to do a "name wallet" it might be better to have a pop-up with only "write name for wallet" on it, so user knows exactly what's going on).
> * I selected a few mainnet and testnet ( the default mainnet selection is a little bit odd, the default had Gnosis selected only), when I was on wallet screen I saw all the networks I selected (main and testnet). When I did a swipe refresh I could see only mainnet (I had last been selecting mainnet). Recommend that on the network selection with this option selected, we show mainnets then testnets, without any switch (ie all on same listview). When user exits back to the wallet page, it should show the mainnets only.
> 
> Once this is working let's update it so that it matches the new spec Tomek designed; this will have to be done carefully though.

@JamesSmartCell Fixed the second issue, but couldn't replicate the first. I checked the code and there are very few references to `NameThisWalletActivity`, is it consistently reproducible on your end?

2022-08-09 11:26 UTC, JamesSmartCell commented
@justindg ok It might have been just an artifact but I also can't reproduce where it jumps to the naming screen, so lets leave that for now.

Try this:

1. Create new wallet
2. Select some mainnets.
3. Select some testnets.

Exit selection.

Screen looks like this:

![screen](https://user-images.githubusercontent.com/12689544/183635978-80a784cb-8c2a-45e0-be78-946fc7b2cb28.jpg)

You can fix it very simply (maybe, if you're receiving a return intent) by sending an instruction to refresh the wallet screen after user finishes their selection. Unless you added a custom function into TokensService to update the filter outside of the normal setup. In which case you should remove that refresh TokensService then it'll work correctly.

2022-08-12 03:55 UTC, justindg commented
> @justindg ok It might have been just an artifact but I also can't reproduce where it jumps to the naming screen, so lets leave that for now.
> 
> Try this:
> 
> 1. Create new wallet
> 2. Select some mainnets.
> 3. Select some testnets.
> 
> Exit selection.
> 
> Screen looks like this:
> 
> ![screen](https://user-images.githubusercontent.com/12689544/183635978-80a784cb-8c2a-45e0-be78-946fc7b2cb28.jpg)
> 
> You can fix it very simply (maybe, if you're receiving a return intent) by sending an instruction to refresh the wallet screen after user finishes their selection. Unless you added a custom function into TokensService to update the filter outside of the normal setup. In which case you should remove that refresh TokensService then it'll work correctly.

This has been fixed

2022-08-13 13:50 UTC, seabornlee commented
@JamesSmartCell I am all done on this PR, transfer test is also enabled and it works well on Görli testnet.

2022-08-19 05:08 UTC, JamesSmartCell approved these changes
@justindg works as expected now. Nice.

2022-08-19 06:03 UTC, JamesSmartCell commented on app/build.gradle
Use 2.6.3 because 2.6.4 requires extra setup

2022-08-19 06:07 UTC, merged