feat: allow copy of NFT contract address from NFTAssetDetailActivity
AlphaWallet/alpha-wallet-android pull request #2840
Opened 2022-09-22 14:33 UTC by micwallace

Pretty much what the title says. This is nice to have as a developer :-)

2022-09-23 08:35 UTC, JamesSmartCell requested changes
Nice :)

Can you change the useView element to use the ```CopyTextView``` element which is how we show a copyable value. This has its own inbuilt copy functionality so it'll simplify the code a little too.

See ```class TransactionDetailActivity``` for usage example, if you need to - essentially:
Layout:
```             
                < com.alphawallet.app.widget.CopyTextView
                android:id="@+id/txn_hash"
                android:layout_width="match_parent"
                android:layout_height="wrap_content" />
```

Code:

```
CopyTextView txHashView = findViewById(R.id.txn_hash);
txHashView.setText("0xADDRESS");
```

2022-10-28 05:11 UTC, justindg commented
Modifications done:

- `TokenInfoView` can now set any text to become copyable via `.setCopyableValue(String text)` 
- Copyable text now displays an icon
- Replaced copy action from long-click to regular click

2022-10-28 05:14 UTC, justindg commented
Preview:

![image](https://user-images.githubusercontent.com/17334718/198508097-096b8b2d-ec3e-42b1-ab24-83fe39fe0c2a.png)

2022-10-28 07:26 UTC, JamesSmartCell approved these changes

2022-10-28 07:26 UTC, merged