Display OpenSea NFT Rarity Data if available
AlphaWallet/alpha-wallet-android pull request #2851
Opened 2022-09-28 05:16 UTC by justindg

- Closes #2843 

![image](https://user-images.githubusercontent.com/17334718/192693373-e579fed4-8723-4759-b397-001946316ae2.png)

2022-09-28 05:42 UTC, seabornlee commented
Nice job! Only two minor feedback:
1. Name `RarityData` can be `Rarity`, according to <Clean Code> naming, a suffix such as Data/Info/Record is redundant.
2. i18n, you can use Google Translator, even not so accurate, it's better than nothing.

2022-09-28 05:43 UTC, seabornlee requested changes
Nice job! Only two minor feedback:

1. Name RarityData can be Rarity, according to naming, a suffix such as Data/Info/Record is redundant.
2. i18n, you can use Google Translator, even not so accurate, it's better than nothing.

2022-09-28 22:56 UTC, JamesSmartCell commented
> Nice job! Only two minor feedback:
> 
> 1. Name RarityData can be Rarity, according to naming, a suffix such as Data/Info/Record is redundant.
> 2. i18n, you can use Google Translator, even not so accurate, it's better than nothing.

On the translation issue - we should take a leaf from Seaborn's book here - I've also started using Google translate for all the regions. It takes a bit longer to do, for future maybe we can write a small script that produces the translations for each language? I think you have to have a google developer license to use the translate API, it used to work for free.

Second thing is storage - should we store these extra values?

2022-09-30 07:39 UTC, JamesSmartCell approved these changes

2022-09-30 10:33 UTC, seabornlee approved these changes

2022-10-01 00:09 UTC, merged