2850 refactor to remove api23 kludges and switches
AlphaWallet/alpha-wallet-android pull request #2868
Opened 2022-10-10 03:01 UTC by seabornlee

- Fix test
- Fix test
- Ignore failure test
- Remove version check code
- Use Java 8 stream API
- Use original web3j lib

2022-10-10 21:13 UTC, JamesSmartCell commented
@seabornlee some of these updates probably might not help readability of the source; where there's a for loop iterating through eg a list or map maybe let's keep it that way for readability/maintainability, but if its a collection then use the streams.

What do you think?

2022-10-13 04:17 UTC, seabornlee commented
Can you comment on several points which you prefer to keep?

2022-10-15 17:14 UTC, JamesSmartCell commented
> Can you comment on several points which you prefer to keep?

Sure, basically anywhere where a 'for' loop would make the code cleaner, readable and maintainable. It would be easier to highlight the areas where this does improve the code rather than the other way round because I think about 90% of the time a 'for' loop is better. I find it very difficult to read or work on the code where this stream style is used, unless it used to traverse a structure that's already a collection, where it appears natural.

2022-10-15 17:26 UTC, JamesSmartCell requested changes
I got a little way into this, then realised that pretty much anywhere where we can do:

```for(data : dataset)``` the code is clearer and more maintainable if we leave it as a for loop.

The streams are good in many places, esp where the structure is like this:

```for (int i=0; i<x; i++)```

Definitely improves that code.

However, please revert to ```for``` anywhere where we use the for loop for traversing a dataset. I think with streams and the short notation we're going to run into maintenance problems further down the line.

2022-10-15 17:26 UTC, JamesSmartCell commented on app/src/main/java/com/alphawallet/app/entity/CovalentTransaction.java
>              try
Please revert to 'for' loop as it's simpler and cleaner

2022-10-15 17:26 UTC, JamesSmartCell commented on app/src/main/java/com/alphawallet/app/entity/CovalentTransaction.java
> +        return Arrays.stream(log_events).filter(le -> le.sender_address != null).findFirst().map(le -> le.sender_address).orElse("");
Please revert to 'for' loop here.

2022-10-15 17:26 UTC, JamesSmartCell commented on app/src/main/java/com/alphawallet/app/entity/EventSync.java
> +        txHashes.forEach(txHash -> TransactionsService.addTransactionHashFetch(txHash, token.tokenInfo.chainId, token.getWallet()));
Please revert to 'for' loop.

2022-10-15 17:26 UTC, JamesSmartCell commented on app/src/main/java/com/alphawallet/app/entity/GasPriceSpread.java
> +        return Arrays.stream(TXSpeed.values()).map(fees::get).filter(Objects::nonNull).findFirst().orElse(null);
Please revert to 'for' loop.

2022-10-15 17:26 UTC, JamesSmartCell commented on app/src/main/java/com/alphawallet/app/entity/GasPriceSpread.java
>              GasSpeed2 gs = fees.get(txs);
Please revert to 'for' loop.

2022-10-15 17:26 UTC, JamesSmartCell commented on app/src/main/java/com/alphawallet/app/entity/GasTransactionResponse.java
> +        result.keySet().forEach(price -> priceSet.put(Integer.parseInt(price), result.get(price)));
Please revert to 'for' loop.

2022-10-15 17:26 UTC, JamesSmartCell commented on app/src/main/java/com/alphawallet/app/entity/nftassets/NFTAsset.java
> +        return Arrays.stream(IMAGE_DESIGNATORS).filter(assetMap::containsKey).findFirst().map(key -> Utils.parseIPFS(assetMap.get(key))).orElse("");
Please revert to 'for' loop.

2022-10-15 17:26 UTC, JamesSmartCell commented on app/src/main/java/com/alphawallet/app/entity/nftassets/NFTAsset.java
> +        return Arrays.stream(SVG_OVERRIDE).filter(key -> assetMap.containsKey(key) && assetMap.get(key).toLowerCase().endsWith("svg")).findFirst().map(key -> Utils.parseIPFS(assetMap.get(key))).orEls
Please revert to 'for' loop.

2022-10-15 17:26 UTC, JamesSmartCell commented on app/src/main/java/com/alphawallet/app/entity/tokens/ERC721Ticket.java
> +        return balanceArray.stream().collect(Collectors.toMap(tokenId -> tokenId, NFTAsset::new, (a, b) -> b));
Please revert to 'for' loop. This is a bit impenetrable what's going on in here, would never be sure exactly what this does without expanding the code back out.

2022-10-15 17:26 UTC, JamesSmartCell commented on app/src/main/java/com/alphawallet/app/entity/tokens/ERC721Ticket.java
> +        balanceArray.stream().filter(value -> value.compareTo(BigInteger.ZERO) != 0 && !nonZeroValues.contains(value)).collect(Collectors.toList());
Please revert to 'for' loop.

2022-10-15 17:26 UTC, JamesSmartCell commented on app/src/main/java/com/alphawallet/app/entity/tokens/ERC721Token.java
> +        return tokenBalanceAssets.values().stream().anyMatch(a -> !a.needsLoading() && !a.requiresReplacement());
Please revert to 'for' loop.

2022-10-15 17:26 UTC, JamesSmartCell commented on app/src/main/java/com/alphawallet/app/entity/tokens/ERC721Token.java
> +        storedBalance = results.stream().map(t -> new BigInteger(t.getTokenId())).collect(Collectors.toCollection(HashSet::new));
Please revert to 'for' loop.

2022-10-27 12:36 UTC, closed without merging