Fix custom RPC node entry
AlphaWallet/alpha-wallet-android pull request #2893
Opened 2022-10-31 03:58 UTC by JamesSmartCell

Fix vulnerability where malicious RPC could be entered via a website inject.

2022-10-31 04:15 UTC, seabornlee requested changes

2022-10-31 04:15 UTC, seabornlee commented on app/src/main/java/com/alphawallet/app/ui/DappBrowserFragment.java
> +    //Display error
I think this comment is redundant as the method name is clear enough.

2022-10-31 04:15 UTC, seabornlee commented on app/src/main/java/com/alphawallet/app/viewmodel/DappBrowserViewModel.java
> +    public boolean addCustomChain(WalletAddEthereumChainObject chainObject) {
Looks like not formatted as the `{` should be on the next line.

2022-10-31 04:15 UTC, seabornlee commented on app/src/main/java/com/alphawallet/app/viewmodel/DappBrowserViewModel.java
> +            if (isValidUrl(thisRpc)) //ensure RPC doesn't contain malicious code
Suggest adding unit test for `isValidUrl` with the malicious payload to ensure it won't pass the gate.

2022-10-31 05:27 UTC, JamesSmartCell commented
Thanks @seabornlee all good observations!

2022-11-02 02:03 UTC, seabornlee approved these changes

2022-11-02 05:01 UTC, merged