Add IPFS connection point
AlphaWallet/alpha-wallet-android pull request #2920
Opened 2022-11-07 08:37 UTC by JamesSmartCell

This PR adds a service for resolving IPFS more reliably than previously - if there's a socket timeout it switches to an alternate IPFS provider.

It also provides a more reliable IPFS resolve as there are fewer paths.

Also 
- Add unit test for the new service
- Resolve specific IPFS hash for the certificate test - note that certificate test is a test for ERC5169 used with IPFS not the actual IPFS resolution itself.

2022-11-07 11:24 UTC, seabornlee requested changes

2022-11-08 01:39 UTC, JamesSmartCell commented on app/src/main/java/com/alphawallet/app/service/IPFSService.java
> +            return "";
Yep, updated

2022-11-08 01:39 UTC, JamesSmartCell commented on app/src/main/java/com/alphawallet/app/service/IPFSService.java
> +    public QueryResponse performIO(String request, String[] headers) throws IOException
Yes, all updated now.

2022-11-08 01:54 UTC, seabornlee approved these changes

2022-11-08 03:21 UTC, seabornlee approved these changes

2022-11-08 04:57 UTC, merged