Refactor Sign Dialogs
AlphaWallet/alpha-wallet-android pull request #2962
Opened 2022-11-22 11:34 UTC by JamesSmartCell

Create single signing dialog and simplify the flow for signing.

Closes #2958

2022-11-22 12:35 UTC, JamesSmartCell commented
@seabornlee can you tweak the AlphaWalletStyle.xml file so it matches the expected text?

2022-11-22 13:06 UTC, seabornlee commented
> @seabornlee can you tweak the AlphaWalletStyle.xml file so it matches the expected text?

Ok.

2022-11-23 15:40 UTC, seabornlee requested changes

2022-11-23 15:40 UTC, seabornlee commented on app/src/main/java/com/alphawallet/app/widget/ActionSheet.java
> +        throw new RuntimeException("Implement setCurrentGasIndex");
How about keep these methods `abstract`, so that developers who want to extend it can get errors in immediately other than runtime.

2022-11-23 15:40 UTC, seabornlee commented on app/src/main/java/com/alphawallet/app/widget/ActionSheetSignDialog.java
> +            FrameLayout bottomSheet = findViewById(com.google.android.material.R.id.design_bottom_sheet);
How about reuse `fullExpand` here?

2022-11-23 15:44 UTC, seabornlee commented
Really awesome refactoring. Can't believe you can get this level of improvements in such short time.

2022-11-28 01:00 UTC, seabornlee approved these changes

2022-11-28 01:03 UTC, justindg commented
I made a PR to this branch here: https://github.com/AlphaWallet/alpha-wallet-android/pull/2968

Kindly consider merging it first, if there are no issues

2022-11-28 01:20 UTC, merged