remove mutually exclusive mode
AlphaWallet/alpha-wallet-android pull request #3052
Opened 2023-01-18 01:44 UTC by seabornlee

- Remove mainnet switch and save whether testnet enabled
- Show selected networks count by adding mainnet count and testnet count
- Refactor: elimilate duplication
- Refactor
- Modify test
- Remove testnet header
- Remove isMainnetActive related code
- Remove check & set isMainnetActive
- Revise import
- Show test net assets in wallet
- Remove network chooser from AddTokenActivity
- Refactor
- Select one network from actived networks
- Remove network chooser from generate payment request
- Remove unused code
- Rename
- Fix
- Remove unused code

2023-01-18 01:54 UTC, seabornlee commented
@JamesSmartCell @justindg 
Could you help to sort the chains in wallet when both mainet and testnet enabled?
I think mainnet should be displayed above all testnet. And BSC testnet should not be in the same group as BSC mainnet.
![Screenshot 2023-01-18 at 09 54 36](https://user-images.githubusercontent.com/735708/213062048-9f60f0be-963a-45a7-87f7-45d4006e9a66.png)

2023-01-27 03:58 UTC, JamesSmartCell requested changes
Just one small improvement.

This PR is as satisfying as expected with the code being simplified :)

2023-01-27 03:58 UTC, JamesSmartCell commented on app/src/main/java/com/alphawallet/app/service/TokensService.java
This can have the boolean removed - it's now always CustomViewSettings.primaryChain

2023-01-28 06:29 UTC, JamesSmartCell approved these changes

2023-01-28 06:31 UTC, JamesSmartCell approved these changes

2023-01-28 06:32 UTC, JamesSmartCell approved these changes

2023-01-28 06:33 UTC, merged