Mixpanel tracking improvements
AlphaWallet/alpha-wallet-android pull request #3179
Opened 2023-04-04 02:59 UTC by justindg

- Closes #2698

Other improvements in this PR:
- Confirmation Dialog result was previously not tracked properly (only in `TokenFunctionActivity` and `SwapActivity`). Moved the implementation to `CreateTransactionInteract` to track every sign and send transaction. Partially closes items in #3028, as some properties require more tinkering to track.
- Created `UserProperties` object under `Analytics` to consolidate items

2023-04-06 15:40 UTC, justindg commented on app/src/main/java/com/alphawallet/app/analytics/Analytics.java
> +        TRANSACTION_COUNT("transactionCount"),
The property names are specified in #2698 

> The enum name and property is duplicated. Suggest using `TRANSACTION_COUNT.name().toLowerCase()`.

2023-04-06 15:40 UTC, justindg commented on app/src/main/java/com/alphawallet/app/analytics/Analytics.java
> +    public static final String PROPS_TRANSACTION_TYPE = "transactionType";
The property names are specified in #3028

> The naming convention does not conform to the upper names.

2023-04-10 11:27 UTC, JamesSmartCell requested changes
Hi @justindg - all looks good code wise - could you rebase with master (not merge!) and update and see if the tests all pass before we merge the PR.

2023-04-10 23:03 UTC, justindg commented
Moved to #3186

2023-04-10 23:03 UTC, closed without merging